hostname p1 
no ipv6 forwarding
!
interface eth1
 ip address 20.20.20.3/24
exit
!
interface eth2
 ip address 30.30.30.3/24
exit
!
interface lo0
 ip address 3.3.3.3/32
exit
!
mpls lsp 300 20.20.20.2 350
mpls lsp 100 30.30.30.4 150
!
