hostname pe1 
no ipv6 forwarding
!
ip route 40.40.40.0/24 20.20.20.3 label 100
!
interface eth1
 ip address 10.10.10.2/24
exit
!
interface eth2
 ip address 20.20.20.2/24
exit
!
interface lo0
 ip address 2.2.2.2/32
exit
!
mpls lsp 350 10.10.10.1 implicit-null
!
