hostname pe2
no ipv6 forwarding
!
ip route 10.10.10.0/24 30.30.30.3 label 300
!
interface eth1
 ip address 30.30.30.4/24
exit
!
interface eth2
 ip address 40.40.40.4/24
exit
!
interface lo0
 ip address 4.4.4.4/32
exit
!
mpls lsp 150 40.40.40.5 implicit-null
!
