frr version 8.4_git
frr defaults traditional
hostname pe1
no ipv6 forwarding
!
interface eth1
 ip address 10.10.10.2/24
 mpls
exit
!
interface eth2
 ip address 20.20.20.2/24
 mpls
exit
!
interface lo0
 ip address 2.2.2.2/32
exit
!
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.10.10.0/24 area 0
 network 20.20.20.0/24 area 0
exit
!
mpls ldp
 router-id 2.2.2.2
 !
 address-family ipv4
  discovery transport-address 2.2.2.2
  !
  interface eth2
  exit
  !
  interface lo0
  exit
  !
 exit-address-family
 !
exit
!
